---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ww-gitops
  namespace: flux-system
spec:
  ingressClassName: nginx
  rules:
  - host: weave.localhost
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ww-gitops-weave-gitops
            port:
              number: 9001
