apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gotk-components.yaml
  - gotk-sync.yaml
  - helm-repositories/sealed-secrets.yaml
  - helm-repositories/tofu-controller.yaml
  - helm-repositories/minio.yaml
  - helm-repositories/ingress-nginx.yaml
  # - terraform/velero.yaml
