apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx-ingress-controller
  namespace: nginx-ingress-controller
spec:
  chart:
    spec:
      chart: nginx-ingress-controller
      version: ">=4.14.0"
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
  interval: 1m
  timeout: 5m
  releaseName: nginx-ingress-controller